### ISSUE TITLE
스포츠 기사 누락된 버튼 레이아웃

### ISSUE THREAD

**Issue by OrigamiDream** [DarkenPages/Naver-Dark#13]
플랫폼: Windows
해상도: FHD
브라우저: Firefox

```css
.news_work .count .sns_share, .sns_share_wrap .share {
    border: 1px solid #404040;
}

.news_work .count .sns_share .sns_share_ico, .sns_share_wrap .share .sp_ico {
    filter: invert(86%);
}

.news_work .setting .article_font, .news_work .setting .font_set .dotum span {
    filter: invert(82.3%);
}

.news_work .setting .font_set {
    border: 1px solid #404040;
    background: #2f2f2f;
    z-index: 1;
}

.news_work .setting .font_set a:hover {
    background: #404040;
}

.spi_lst .spi_lst_release {
    background-color: #2f2f2f;
    border: 1px solid #404040;
}

.spi_default a {
    color: #cacaca;
}

.spi_btn_release .spi_lst_release a.spi_input_copyurl, .spi_sns_share .spi_lst .spi_btn_release .spi_lst_release a.spi_input_copyurl, .spi_onebtn .spi_lst .spi_btn_release .spi_lst_release a.spi_input_copyurl {
    color: #cacaca;
    border: 1px solid #404040;
    background-color: #404040;
}

.spi_btn_release .spi_lst_release a.spi_btn_copyurl, .spi_sns_share .spi_lst .spi_btn_release .spi_lst_release a.spi_btn_copyurl, .spi_onebtn .spi_lst .spi_btn_release .spi_lst_release a.spi_btn_copyurl {
    color: #cacaca !important;
    border: 1px solid #404040;
}
```
