### ISSUE TITLE
네이버 메인 스페셜 로고 인버트

### ISSUE THREAD

**Issue by OrigamiDream** [DarkenPages/Naver-Dark#15]
플랫폼: macOS Catalina
해상도: 5K
브라우저: Safari
```css
.area_logo .special_img {
    filter: invert(85.5%) hue-rotate(-180deg);
}
```
