### ISSUE TITLE
네이버 로그인 추가 레이아웃

### ISSUE THREAD

**Issue by OrigamiDream** [DarkenPages/Naver-Dark#16]
플랫폼: macOS
해상도: 5K
브라우저: Safari
```css
.diaper_banner, .otp_step_banner {
    filter: invert(86%) hue-rotate(-180deg);
}
```
