### ISSUE TITLE
네이버 메인 섹션 버튼 svg 로 교체예정

### ISSUE THREAD

**Issue by OrigamiDream** [DarkenPages/Naver-Dark#18]
플랫폼: macOS
해상도: 5K
브라우저: Safari

네이버 검색 페이지에서의 섹션은 대부분 svg 처리로 되어있는것에 착안,
이를 이용하여 네이버 메인의 섹션 버튼들을 가능한 한 전부 svg 로 처리하기로 함.

N Pay 나 네이버TV 같은 경우는 직접 만들거나 user-script 를 응용해야하는 상황이 될 수 있음.

예제 CSS
```css
.area_navigation .an_a.mn_comic:after {
    color: #cacaca;
    content: '웹툰';
    font-weight: bold;
    font-family: 'NanumSquare';
    font-size: 14px;
    top: -0.5px;
    position: absolute;
    overflow: auto;
    width: 100%;
}
```
