### ISSUE TITLE
a 태그 고대비 설정

### ISSUE THREAD

**Issue by OrigamiDream** [DarkenPages/Naver-Dark#21]
플랫폼: macOS
해상도: 5K
브라우저: Safari

```css
a, a:link {
    color: #576882;
}

a:visited {
    color: #99209b;
}
```
를
```css
a, a:link {
    color: #7474e3;
}

a:visited {
    color: #e177e3;
}
```
로 교체
