### ISSUE TITLE
네이버 포스트 삭제된 댓글 레이아웃

### ISSUE THREAD

**Issue by OrigamiDream** [DarkenPages/Naver-Dark#23]
플랫폼: macOS
해상도: 5K
브라우저: Safari
주소: https://post.naver.com/viewer/postView.nhn?volumeNo=27773850&memberNo=41062464
```css
.u_cbox .u_cbox_type_delete .u_cbox_text_wrap, .u_cbox .u_cbox_type_blind .u_cbox_text_wrap {
    color: #fff;
}
```
