### ISSUE TITLE
네이버 검색 어학사전 레이아웃 누락

### ISSUE THREAD

**Issue by OrigamiDream** [DarkenPages/Naver-Dark#25]
플랫폼: macOS
해상도: 5K
브라우저: Safari
```css
.dic_jp .lang_type, .dic_jp .txt_ex strong {
    color: #fff;
}
```
