### ISSUE TITLE
네이버 메인 누락 레이아웃

### ISSUE THREAD

**Issue by OrigamiDream** [DarkenPages/Naver-Dark#33]
플랫폼: macOS
해상도: 5K
브라우저: Safari
```css
.btmbanner_list .bl_d {
    color: #cacaca;
}

.section_election .se_wrap {
    background: #242424;
    border: 1px solid #404040;
}

.section_election .se_title, .section_election .se_status.se_ico_early1 {
    filter: invert(86%) hue-rotate(-180deg);
}

.section_election .se_subtitle_wrap .se_sub_link {
    color: #cacaca;
}

.section_election .se_info_wrap .se_point+.se_st {
    color: #fff;
}

.section_election .se_info_wrap .se_point+.se_st:before {
    background-color: #7474e3;
}

.section_election .se_info_wrap .se_point, .section_election .se_vote {
    color: #7474e3;
}
```
