### ISSUE TITLE
네이버 메인 페이 결제 내역 바로가기 색상

### ISSUE THREAD

**Issue by OrigamiDream** [DarkenPages/Naver-Dark#37]
플랫폼: macOS
해상도: 5K
브라우저: Safari
코드:
```css
.svc_blank .svc_msg_box .btn_type.btn_green {
   color: #242424;
}
```
위 코드는 기존 값에서 수정되어져야 할 값을 의미합니다.
