### ISSUE TITLE
네이버 총선 투표 당일 레이아웃

### ISSUE THREAD

**Issue by OrigamiDream** [DarkenPages/Naver-Dark#39]
플랫폼: macOS
해상도: 5K
브라우저: Safari
코드:
```css
.vote_count_banner .banner_area {
	background: #404040;
}

.vote_count_banner .banner_text:before, .vote_count_banner .banner_text .time, .vote_count_banner .banner_text:after {
	filter: invert(78%) hue-rotate(-180deg);
}

.turnout_graph .survey_type_line .survey_cont:before, .turnout_graph .bar_graph, .turnout_graph .survey_type_bar_v .survey_cont:before, .turnout_graph .bar_lst {
	filter: invert(86%) hue-rotate(-180deg);
}

.turnout_data .data_info .noti {
	color: #cacaca;
}

.turnout_data .data_info .bar {
	background-color: #404040;
}

.cont_box .btn_cont_more {
	color: #cacaca;
}
```
