### ISSUE TITLE
검색 누락된 css class selector 수정

### ISSUE THREAD

**Issue by OrigamiDream** [DarkenPages/Naver-Dark#6]
플랫폼: Windows
해상도: FHD
브라우저: Firefox

다음으로 설정
```css
.sp_shop_default .partial_noti .point {
    color: #fff;
}
```
